---
name: boulder

features:
  use_dns_addresses: true

update:
  canaries: 1
  canary_watch_time: 30000-1200000
  max_in_flight: 1
  serial: true
  update_watch_time: 5000-1200000

instance_groups:
- name: mysql
  azs:
  - z1
  persistent_disk_type: 10GB
  instances: 1
  vm_type: minimal
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: mysql
    release: cf-mysql
    properties:
      cf_mysql:
        mysql:
          admin_password: "((mysql_root_password))"
          galera_healthcheck:
            db_password: "((mysql_galera_healthcheck_password))"
            endpoint_password: "((mysql_galera_healthcheck_endpoint_password))"
          cluster_health:
            password: "((mysql_cluster_health_password))"
          tls:
            ca_certificate: "((mysql_server_cert.ca))"
            server_certificate: "((mysql_server_cert.certificate))"
            server_key: "((mysql_server_cert.private_key))"
          seeded_databases:
          - name: boulder
            username: boulder
            password: "((mysql_boulder_password))"
- name: boulder
  azs:
  - z1
  instances: 1
  vm_type: minimal
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: sa
    release: boulder
    properties:
      tls:
        private_key: ((sa_cert.private_key))
        certificate: ((sa_cert.certificate))
        ca: ((sa_cert.ca))
      db:
        database: boulder
        username: boulder
        password: "((mysql_boulder_password))"
      grpc:
        port: 10043
      debug:
        port: 10084
  - name: va
    release: boulder
    properties:
      tls:
        private_key: ((va_cert.private_key))
        certificate: ((va_cert.certificate))
        ca: ((va_cert.ca))
      grpc:
        port: 10067
      debug:
        port: 10012
  - name: ca
    release: boulder
    properties:
      tls:
        private_key: ((ca_cert.private_key))
        certificate: ((ca_cert.certificate))
        ca: ((ca_cert.ca))
      ca:
        private_key: ((actual_ca.private_key))
        certificate: ((actual_ca.certificate))
      grpc:
        port: 10054
      debug:
        port: 10059

variables:
- name: mysql_root_password
  type: password
- name: mysql_galera_healthcheck_password
  type: password
- name: mysql_galera_healthcheck_endpoint_password
  type: password
- name: mysql_cluster_health_password
  type: password
- name: mysql_boulder_password
  type: password
- name: mysql_ca
  type: certificate
  options:
    is_ca: true
    common_name: mysql
- name: mysql_server_cert
  type: certificate
  options:
    ca: mysql_ca
    common_name: mysql
    extended_key_usage:
    - server_auth
- name: grpc_ca
  type: certificate
  options:
    is_ca: true
    common_name: boulder_grpc_ca
- name: sa_cert
  type: certificate
  options:
    ca: grpc_ca
    common_name: sa
    alternative_names: ["*.sa.default.boulder.bosh"]
    extended_key_usage:
    - client_auth
    - server_auth
- name: va_cert
  type: certificate
  options:
    ca: grpc_ca
    common_name: va
    alternative_names: ["*.va.default.boulder.bosh"]
    extended_key_usage:
    - client_auth
    - server_auth
- name: ca_cert
  type: certificate
  options:
    ca: grpc_ca
    common_name: ca
    alternative_names: ["*.ca.default.boulder.bosh"]
    extended_key_usage:
    - client_auth
    - server_auth
- name: actual_ca
  type: certificate
  options:
    is_ca: true
    common_name: actual_ca

releases:
- name: boulder
  version: latest
- name: cf-mysql
  url: https://bosh.io/d/github.com/cloudfoundry/cf-mysql-release?v=36.10.0
  version: 36.10.0
  sha1: dadf405f2305b6f9b625c1e07bd58aa93caf3cbc

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest
